
#=================================================================================
# 容器相关设置

server:
  compression:
    enabled: true
    mime-types: 'application/json,text/css,text/html'
    min-response-size: 2048

debug: true
logging:
  config: classpath:log4j2.xml
#=================================================================================
# spring 组件相关设置

spring:
  application:
    name: springboot-simple-demo
  profiles:
    active: 'dev'
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      use-global-data-source-stat: true
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      slf4j:
        enabled: true
      wall:
        enabled: true
      web-stat:
        enabled: true
        url-patterns: '/*'
        exclusions: '*.gif,*.jpg,*.jpeg,*.png,*.bmp,*.swf,*.ico,*.woff,*.woff2,*.ttf,*.eot,*.js,*.css,*.html,*.htm,/druid/*'
      stat-view-servlet:
        enabled: true
        url-mappings: '/druid/*'
        allow: 127.0.0.1
        deny: 192.168.2.1
        login-username: admin
        login-password: 123456
        reset-enable: false
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: 'text/html'
    prefix: 'classpath:/templates/'
    suffix: '.html'
    cache: false



#=================================================================================
# 其他辅助框架相关配置
mybatis-plus:
  mapper-locations: 'classpath:/mapper/*.xml'
  typeAliasesPackage: 'com.gitnavi.springboot.springbootsimpledemo.pojo.entity'
  typeEnumsPackage: 'com.gitnavi.springboot.springbootsimpledemo.pojo.entity.enums'
  global-config:
    id-type: 1
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#=================================================================================
# 自定义参数相关配置


#=================================================================================